import GenericPolicy from "./GenericPolicy";

export default function Exemption2257() {
  const toc = [
    { id: "statement", label: "1. Statement" },
    { id: "fictional", label: "2. Fictional Characters" },
    { id: "zero-tolerance", label: "3. Zero Tolerance" },
    { id: "contact", label: "4. Contact" },
  ];
  return (
    <GenericPolicy title="18 U.S.C. § 2257 Compliance Statement" updated="March 17, 2026" toc={toc}>
      <section id="statement" className="space-y-2">
  <h3 className="mt-4 text-lg sm:text-xl font-semibold text-[#B8A3F6] tracking-tight">1. Statement</h3>
  <p className="text-sm">
          All visual content appearing on shefeels.ai — including images, avatars, and video — is entirely generated by artificial intelligence. No actual human beings were photographed, filmed, or otherwise depicted in the creation of any content on this Platform.
        </p>
        <p className="text-sm">
          As such, the record-keeping requirements of 18 U.S.C. § 2257 and 28 C.F.R. Part 75 do not apply to any content produced, hosted, or distributed by shefeels.ai or its operator, JLHL MANAGEMENT LTD.
        </p>
      </section>

      <section id="fictional" className="space-y-2">
  <h3 className="mt-4 text-lg sm:text-xl font-semibold text-[#B8A3F6] tracking-tight">2. Fictional Characters</h3>
  <p className="text-sm">
          All characters, personas, and digital representations on shefeels.ai are entirely fictional. They are not based on, modeled after, or derived from any real individuals.
        </p>
      </section>

      <section id="zero-tolerance" className="space-y-2">
  <h3 className="mt-4 text-lg sm:text-xl font-semibold text-[#B8A3F6] tracking-tight">3. Zero Tolerance</h3>
  <p className="text-sm">
          JLHL MANAGEMENT LTD maintains an absolute zero-tolerance policy regarding the depiction of minors. This commitment is enforced through multiple layers of protection:
        </p>
        <ul className="list-disc pl-5 mt-1 space-y-1 text-sm">
          <li>Automated safety filters built into our AI generation pipeline.</li>
          <li>Human review processes to audit and verify compliance.</li>
          <li>Immediate removal of any flagged or reported content.</li>
          <li>Account termination for attempts to generate prohibited content.</li>
        </ul>
      </section>

      <section id="contact" className="space-y-2">
  <h3 className="mt-4 text-lg sm:text-xl font-semibold text-[#B8A3F6] tracking-tight">4. Contact</h3>
  <p className="text-sm">
          If you have any questions regarding this compliance statement, please contact us at: <a className="underline" href="mailto:legal@shefeels.ai">legal@shefeels.ai</a>
        </p>
      </section>
    </GenericPolicy>
  );
}
